# Use root/example as user/password credentials
version: "3.1"

services:
  tomcat:
   image: tomcat
   ports:
     - 8585:8080
   volumes:
     - ./tomcat:/usr/local/tomcat/webapps
  postgres:
    image: postgres
    volumes:
      - ./db-setup/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    restart: always
    ports:
      - 5532:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
  jenkins:
      image: jenkins/jenkins:lts
      privileged: true
      user: root
      ports:
        - 8081:8080
        - 50000:50000
      container_name: jenkins
      volumes:
        - ./jenkins:/var/jenkins_home
  adminer:
    image: adminer
    restart: always
    ports:
      - 8282:8080
